# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='rating',
            field=models.CharField(default=3, max_length=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='Mexican', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='restaurants',
            field=models.ManyToManyField(to='dealioApp.Restaurant'),
        ),
    ]
