# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0002_auto_20170224_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('American', 'American'), ('Mexican', 'Mexican'), ('Chinese', 'Chinese')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ManyToManyField(to='dealioApp.FoodGenre'),
        ),
    ]
