# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0003_auto_20170225_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('American', 'American'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Mexican', 'Mexican'), ('Italian', 'Italian')], default='Mexican', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FoodGenre',
        ),
    ]
