# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealioApp', '0004_auto_20170225_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='John Smith', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='password', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promotion',
            name='rating',
            field=models.CharField(choices=[('Rating:(1-5)', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')))], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Food Choice', (('American', 'American'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Mexican', 'Mexican'), ('Italian', 'Italian')))], max_length=10),
        ),
    ]
